### ISSUE TITLE
Error about a QThread being deleted while running

### ISSUE THREAD

**Issue by aalex** [Xmodal/dynamiclight#100]
When we quit, there is an error about a QThread being deleted while still running.

```
QThread: Destroyed while thread is still running
```

**Comment by simondemeule** [comment]
This is partially resolved as of 72d1a22. The compute thread was not being shut down when the application closed. However now there appears to be a new memory allocation problem involving `Facade`, which only occurs if the generator was selected in the UI before closing the application. For some reason the `QSharedPointer` holding a reference to `Facade` attempts to delete twice.
