### ISSUE TITLE
Find an efficient way to share vector / list data from C++ to QML

### ISSUE THREAD

**Issue by simondemeule** [Xmodal/dynamiclight#107]
For the application to be able to display certain graphics, it is necessary to find an efficient way to share vector / list based data from C++ to QML. This is made complex by the fact that sharing `QSharedPointer` with QML is difficult or impossible. Different solutions have to be tried out, and some profiling / efficiency testing has to be done. This is necessary for #8, #75, #76.

**Comment by simondemeule** [comment]
@lucidism I've played around with implementing one of the solutions you initially proposed with the initial prototypes — the solution where we create the circular buffer in JavaScript, which should minimize data exchange from C++ to QML, since we only need to send a single value per generator update, rather than a full array. To my surprise this has essentially no performance advantage. This might be because QML to C++ communication actually uses pointers internally to share the data — meaning the solutions could be functionally identical. I'll have to do some more research on that.

You can try out this version of the history graph on branch `simplify-output-monitor-history`. I've set up a test case for benchmarking — I've added 4 generators and set the history buffer size to 128. This can be compared to the more memory bandwidth demanding solution on branch `fix/output-monitor-history-access` — this has the same benchmarking setup. You'll see that they both use a gross amount of CPU and seem a bit stuttery. The difference between the two seems negligible.

The thing is, the JavaScript-side buffer is the optimal solution in terms of minimizing memory bandwidth. The fact that the "dumb" C++ to QML array strategy performs equally well seems to indicate that memory bandwidth isn't the bottleneck. Drawing the canvas is much more likely the problem. We should look into implementing this with a shader — there has to be a simple way to take our buffer and transform it into a vertex array that can easily be rendered by a very simple vertex / fragment shader combo.

I think we can probably close this issue and open a new one specific to the matrix, as it seems the solution may rely on images rather than on the vector sharing strategies we have here.

I also suggest we merge `simplify-output-monitor-history` into `dev` (maybe not this version, I'll remove the benchmarking setup before merging if we go that route) and create a new issue for rewriting the `HistoryGraph` paint routine as a shader. I also wouldn't delete the `fix/output-monitor-history-access` branch, in case we want to revert to this strategy later on for some reason.

**Comment by lucidism** [comment]
>I think we can probably close this issue and open a new one specific to the matrix, as it seems the solution may rely on images rather than on the vector sharing strategies we have here.

@simondemeule agreed. I kind of realized as I was developing the neuron matrix that plugging arrays into a fragment shader, especially if they're dynamic, is basically impossible (QML bug, as it turns out), so we'd have had to resort to images in any case. we can close this issue for sure. I'll try to implement the "vertex array" method you mentioned, though I think passing an image as input is still our safest bet. we'll see

**Comment by lucidism** [comment]
some food for thought: https://doc.qt.io/archives/qt-4.8/qdeclarativeimageprovider.html

**Comment by simondemeule** [comment]
> passing in arrays as uniforms into a fragment shader, especially if they're dynamic, is basically impossible (QML bug, as it turns out)

That really sucks. Sometimes I feel we are just trying to navigate a minefield of bugs and odd design decisions with Qt.

> I'll try to implement the "vertex array" method you mentioned, though I think passing an image as input is still our safest bet. we'll see

@lucidism the point of passing a vertex array is that it defines the mesh geometry that will be rendered by the shader — meaning we can use the GPU to draw the line rather than the CPU. This is also different from passing an array of uniforms, and will necessarily be supported (it is impossible for a graphics shader to work without this). This isn't possible using a ShaderEffect as far as I know, since the geometry can only be a rectangle or some kind of grid — we need full control over the geometry — we'd have to use Qt 3D I believe. One other cool thing with this is that we should be able to use the vertex array as our circular buffer, and do the fancy indexing stuff in the shader.

I'll make the changes on `simplify-output-monitor-history`, create the pull request, and create the bew issue.

**Comment by simondemeule** [comment]
@lucidism it seems the matrix-specific issue already exists. See #75.

**Comment by lucidism** [comment]
> @lucidism the point of passing a vertex array is that it defines the mesh geometry that will be rendered by the shader — meaning we can use the GPU to draw the line rather than the CPU. This is also different from passing an array of uniforms, and will necessarily be supported (it is impossible for a graphics shader to work without this). This isn't possible using a ShaderEffect as far as I know, since the geometry can only be a rectangle or some kind of grid — we need full control over the geometry — we'd have to use Qt 3D I believe. One other cool thing with this is that we should be able to use the vertex array as our circular buffer, and do the fancy indexing stuff in the shader.

interesting! I'll have to look a bit more into 3D shaders, I haven't had much of a chance to experiment with those, especially not geometry shaders. though from what you've said, it does seem like that method would maximize efficiency in a number of ways. thanks for the heads-up!
