### ISSUE TITLE
Fix shader compile error

### ISSUE THREAD

**Issue by simondemeule** [Xmodal/dynamiclight#111]
#108 seems to have introduced a shader compile error:

`QOpenGLShader::​link: ERROR: Input of fragment shader 'qt_TexCoord0' differs in type/qualifiers to that written by vertex shader`
`ERROR: Input of fragment shader 'qt_TexCoord0' not written by vertex shader`

`shader compilation failed: `
`"ERROR: Input of fragment shader 'qt_TexCoord0' differs in type/qualifiers to that written by vertex shader\nERROR: Input of fragment shader 'qt_TexCoord0' not written by vertex shader\n"`
`QOpenGLShader::​link: ERROR: Input of fragment shader 'qt_TexCoord0' differs in type/qualifiers to that written by vertex shader`
`ERROR: Input of fragment shader 'qt_TexCoord0' not written by vertex shader`

**Comment by lucidism** [comment]
@simondemeule that's kind of a funny one, I haven't had any error of this kind on my end. comparing with [the docs on layer effects](https://doc.qt.io/qt-5/qml-qtquick-item.html#combined-with-shadereffects) though, I did notice that `qt_TexCoord0` is defined in this context as a `highp vec2`, and not a `vec4`, so this might be what's at cause here.

I've just created a new branch `fix/shader-compile` which implements this change, could you check it out and let me know if you still have the error? thanks!

**Comment by simondemeule** [comment]
@lucidism that fixes it!
