### ISSUE TITLE
Actually run the generator in the backend

### ISSUE THREAD

**Issue by aalex** [Xmodal/dynamiclight#20]
Actually run the generator. See #5

Details:

- It might involve multi-threading
- Question: Maybe one thread per model?
- It updates at about 60 or 120 Hz

**Comment by simondemeule** [comment]
pseudo-pseudo code for multi-threaded rendering

* build a graph of dependencies (connections) between generators.
* create a coordinating thread that has a stack of generators that are ready to be rendered.
* put all generators that have no dependencies in the stack.
* create rendering threads and let them pick generators from the stack. the generators are immediately removed from the stack.
* once a rendering thread is done with a generator, it checks all dependent generators to see if they are ready to render (meaning the generators they depend on are all done rendering). any generator that is ready gets pushed onto the ready stack.

notes

* for feedback, a unit delay node is absolutely necessary.
* generators need a few attributes:
    * done rendering
    * pointers to other generators that encode the graph structure
* optimizing this is tricky. the most important decision we make is how we pick from the ready stack. the goal is to always use as many rendering threads as possible at once.
* should we just spawn as many rendering threads as there are cores on the machine, or clamp it down to the maximum level of parallelism that could be encountered while rendering? that involves a bit of math.

**Comment by simondemeule** [comment]
Added a pull request to the dev branch for a backend model that implements the minimum required to run generators in the backend. It runs a single thread for running generators separate from the GUI thread. 

It still has some timing issues — it will become unstable when other applications are taking up a lot of CPU, and also when the app is not the "topmost" or "active" app on the operating system. Unfortunately when it does, it becomes unusable. The framerate crashes down from 30Hz to less than 1 update per 5 seconds. This might be a bug with QTimer, or this might just be a bad implementation. More investigation is required.

**Comment by aalex** [comment]
I believe we can consider this done, and create a bug report for the issues you describe in your comment above, @simondemeule !

**Comment by aalex** [comment]
Done as of 4528c5a9f18870738b1926376b2a1ec0388f46e7

**Comment by aalex** [comment]
Created issue #49 where I've put the issues mentioned in the comment to this item.
