### ISSUE TITLE
Receive OSC from the outside into the inputs of my generator

### ISSUE THREAD

**Issue by alx-s** [Xmodal/dynamiclight#65]
As an artist I want to send OSC messages to the inputs of my generator 

Acceptance criteria:

- Receive one OSC message that contains the different input values
- Parse the message to the different inputs (value 0 to input 0, value 1 to input 1...)
- Clip the values as floats between 0 and 1
- Set the input port (by default 1320)
- Set the address (by default /[name_generator]/inputs)
- The value received is added to the current value of the neurons that are selected as input

Technical details:

- ...
- ...

**Comment by simondemeule** [comment]
Working as of c6bc124, although there probably is some more room for optimisation. I still want to do some more testing and cleanup before we can pull this into `dev`.
